### ISSUE TITLE
Non-alpine images?

### ISSUE THREAD

**Issue by breandan** [docker-library/docker#127]
Are there any plans to publish a non-Alpine based image? Alpine seems to have [some issues](https://kubedex.com/follow-up-container-scanning-comparison/) with image scanning and mapping CVEs. And now that Ubuntu is [minimal by default](https://blog.ubuntu.com/2018/07/09/minimal-ubuntu-released), there seems to be fewer reasons to use it. It would be nice to provide official support for DIND/DOOD on Ubuntu.

**Comment by tianon** [comment]
> Are there any plans to publish a non-Alpine based image?

Not especially -- IMO, CVE mapping isn't a real solid justification for the added maintenance/churn.  Is there a usability concern with Alpine?  In my experience, using Docker-in-Docker is pretty self-contained, and it's a pretty rare use case where something non-Alpine is necessary (which makes sense, given that containers not relying on the specifics of the "host" / `dockerd` environment is kind of the entire point).

**Comment by tianon** [comment]
Closing given that this isn't something we're currently considering.  If there's a solid justification to be made for the added maintenance burden of supporting addition variants, we'll reopen and reconsider. :+1:

**Comment by ammario** [comment]
A `dind` image for Ubuntu would help the Docker-based, immutable dev environment movement.

I will probably be working on something like this, would be happy to do my work as a change to this repo.

**Comment by felipecrs** [comment]
I wrote a `dind` version inspired by this image using `ubuntu` as the base for my own use in [`jenkins-agent-dind`](https://github.com/felipecrs/jenkins-agent-dind). I'm using it for more than 1 year already and it's pretty solid, but probably overkill if not to be used for its sole purpose.

An official `dind` based on Ubuntu would greatly simplify the maintenance of my image, as a big part of its Dockerfile is due to the tricks to make it work.
