### ISSUE TITLE
Swarm inside Kubernetes

### ISSUE THREAD

**Issue by jcheroske** [docker-library/docker#143]
I have this bizarro use case where I'd like to deploy a workload on kubernetes, but I'd then like one of the containers to be managed via docker swarm and Portainer. Can anyone here imagine a way to make this happen? I ssh'd into a k8s cluster node and tried just issuing a `docker swarm join`, but I got the following error:
```
Error response from daemon: --live-restore daemon configuration is incompatible with swarm mode
```
I thought maybe there was a way to use docker-in-docker to do what I want, but I can't see it.

Thanks for any help at all,

Jay

**Comment by wglambert** [comment]
You'd probably want to try asking [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). 
Since these repositories aren't a forum but an issue tracker

**Comment by jcheroske** [comment]
Ok thanks
