### ISSUE TITLE
Proposal: package with some pre-loaded images

### ISSUE THREAD

**Issue by ebuildy** [docker-library/docker#148]
**Use case**

In our CI env, test servers have no internet access, so we currently use a private registry to act as a cache: 
1- pull from web then push on private registry
2- test servers: consume from private registry

As we use Docker in Docker, I override the dind image to store some images, with ``docker save`` and ``docker load``. This work pretty well, so I am wondering if it's a good practice, if yes , here my proposal:

**Proposal**

"``docker:dind``, at startup, should read a /images folder and execute ``docker load`` for all tar files found."

(exactly what mysql did at https://github.com/docker-library/mysql/blob/696fc899126ae00771b5d87bdadae836e704ae7d/5.5/docker-entrypoint.sh#L189).

**Comment by tianon** [comment]
I think it's a perfectly fine/sane practice, but I don't think it belongs in the official image -- we currently provide _very little_ additional behavior above and beyond what Docker itself provides out-of-the-box with the goal being to provide an authentic upstream experience.

FWIW, I think once Docker switches to using the `containerd` content-store, this will likely get easier, since the content store and the snapshotter storage get de-coupled _and_ the content store should be fillable without any sort of privileges (since it will "just" be downloading tarballs from the registry and storing them as-is so that they stay appropriately content-addressable), so you might even be able to do better than `docker save` and `docker load` at some point soon-ish! See https://github.com/moby/moby/issues/38043 for the official proposal around that.
