### ISSUE TITLE
Error initilizing network controller: error obtianing network instance:failed to create nat chain docker: iptables(v1.6.2):cannot initilize iptables table 'nat' table does not exist

### ISSUE THREAD

**Issue by chenliu1993** [docker-library/docker#150]
I am using containerd ctr built from containerd source code to run dind. But I got the error described as the title. Is there any way I can solve this error? Or just skip 'nat' to use other methods? 
My command is :
ctr --debug run --privileged --rm --no-pivot --net-host --mount type=bind,src=/some,dst=/var/lib/docker,options=rbind:ro docker.io/library/docker:dind run
kernel is Linux 4.9.137-1.ph2 built by myself. And no support for nat.
Much appreciated for the help!
![image](https://user-images.githubusercontent.com/13761170/55525641-7a7b7200-56c4-11e9-9f12-f5c15715ee73.png)

**Comment by tianon** [comment]
If your kernel has no support for NAT, it likely won't be able to run Docker very well.

Closing, since this isn't an issue with the image (and is really an issue with your environment/configuration). For more help, I'd suggest trying [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).

**Comment by chenliu1993** [comment]
> If your kernel has no support for NAT, it likely won't be able to run Docker very well.
> 
> Closing, since this isn't an issue with the image (and is really an issue with your environment/configuration). For more help, I'd suggest trying [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).

Still got one questions. Where does this "iptables -t nat -N DOCKER" comes from? I can't find the code at this repo.

**Comment by tianon** [comment]
That code is part of Docker -- this repo is just packaging for the
officially-released binaries.
