### ISSUE TITLE
Include docker-app plugin with docker image

### ISSUE THREAD

**Issue by kinghuang** [docker-library/docker#156]
*Copied from docker/app#532*

**Description**

Can the docker-app 0.8.0 CLI plugin be included with the [docker](https://hub.docker.com/_/docker/) 19.03 image (currently at docker:19.03.0-beta3)?

I previously asked for a docker-app image in docker/app#367, similar to the [docker/compose](https://hub.docker.com/r/docker/compose) image. But, with docker-app now functioning as a CLI plugin, it would be preferable to have it as part of the docker image.

**Steps to reproduce the issue:**

1. Run a container with the docker:19.03.0-beta3 image.
2. Attempt to use `docker app` commands.

**Describe the results you received:**

`docker app` commands aren't available. The docker-app CLI plugin is not included with the docker image.

**Describe the results you expected:**

Be able to use `docker app` commands.

**Additional information you deem important (e.g. issue happens only occasionally):**

There is currently no official image with Docker App, either as a plugin or as a standalone command. I need an image for CI jobs that use Docker App.

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.0-beta3
 API version:       1.40
 Go version:        go1.12.4
 Git commit:        c55e026
 Built:             Thu Apr 25 02:55:45 2019
 OS/Arch:           linux/amd64
 Experimental:      false

```

**Output of `docker-app version`:**

Docker App is not available in the docker image.

**Output of `docker info`:**

N/A

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by tianon** [comment]
This image faithfully publishes whatever bits Docker officially provides via https://download.docker.com/linux/static/ (installing necessary dependencies and some very short scripts to help with usage in minor ways).

**Comment by tianon** [comment]
To put that another way, I don't think it makes sense for us to officially bundle any additional CLI (or otherwise) plugins that Docker's standard distribution does not include (since our main goal is to be a faithful representation of Docker's upstream bits).

**Comment by kinghuang** [comment]
Ah, ok. I'll close this request and focus on asking for a docker-app image. Thanks!

**Comment by ijc** [comment]
FWIW my reading of https://github.com/docker-library/docker/issues/156#issuecomment-489245797 is that we should (try and) arrange for plugins to be part of https://download.docker.com/linux/static/ and then it would be possible to include them in this image. @tianon did I understand you correctly?

**Comment by tianon** [comment]
I mean, yeah, if it's intended to be part of a standard distribution of Docker, it should be included with those "standard distribution" artifacts, right? :innocent: :+1:

IMO it's kind of strange for these to be plugins but also included by default (instead of just having a way for folks to add it easily themselves), but that's a digression. :sweat_smile:

**Comment by teohhanhui** [comment]
`docker/app` and `docker/buildx` are included as plugins in `docker-ce` since Docker 19.03: https://github.com/docker/docker-ce-packaging/pull/309

**Comment by tianon** [comment]
Sure, but from my understanding, they're still not included in the official static bundles under https://download.docker.com/linux/static/ (or else we'd already have them included, since those are the bundles we consume as-is).

**Comment by wedi** [comment]
buildx is included in all installation bundles for macOS, Windows and Linux for years now. The official [buildx installation docs](https://docs.docker.com/buildx/working-with-buildx/#install) on docs.docker.com state that buildx is included in those packages. So, even if it was some package maintainers decision a few years back to include it for the fun of it, this is the officially endorsed way of installing and using buildx (now).

Yes, the buildx binaries are still not available from download.docker.com but looking at the docs and the eco system in a whole it seems safe to assume that they are not omitted for being unofficial or too experimental but because of an internal workflow that just works and sees no pressure to change.

It's almost three years since you closed this issue. Today Docker [states](https://docs.docker.com/develop/develop-images/build_enhancements/) _"Docker Build is one of the most used features of the Docker Engine - users ranging from developers, build teams, and release teams all use Docker Build."_. Taking into account that buildx is here to stay and an officially endorsed part of the release bundles for all major OS and only missing from the docker images, I am asking you to reconsider this decision.

**Comment by daveisfera** [comment]
`buildx` is also where features are being added and today was advertised with statements like ["why you should start to use it on your Dockerfiles"](https://www.docker.com/blog/image-rebase-and-improved-remote-cache-support-in-new-buildkit/), so can it please be added?
