### ISSUE TITLE
nsswitch.conf returned a non-zero code: 1

### ISSUE THREAD

**Issue by jicki** [docker-library/docker#163]
docker build Error

[ ! -e /etc/nsswitch.conf ] && echo 'hosts: files dns' > /etc/nsswitch.conf  returned a non-zero code: 1

**Comment by wglambert** [comment]
Your test construct evaluates to false which gives an exit code of 1, and since it's not captured by an if/then statement its output is captured by the Docker builder and it exits.

If you put it in an if/then statement the evaluation can be false without the whole line being false.

The example below: If the test construct is false it will echo its exit code which is 1, and then getting the actual exit code of the whole command is 0 because there's no error, the loop exited cleanly
```console
$ echo test > file
$ if [ ! -e file ]; then echo 'changed' > file; else echo $?; fi
1
$ echo $?
0
```

http://tldp.org/LDP/abs/html/testconstructs.html
- An if/then construct tests whether the exit status of a list of commands is 0 (since 0 means "success" by UNIX convention), and if so, executes one or more commands.

If you have further questions you should try asking [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repositories are for issues with the image and not necessarily for questions of usability
