### ISSUE TITLE
Use of the "stable" images tags

### ISSUE THREAD

**Issue by toadjaune** [docker-library/docker#178]
Hi everybody !

I'm opening this issue after suffering from two recent behaviour changes in the `dind` images (#175  and #170).

This happened despite using `stable` and `dind-stable` tags.

As far as I can tell, there is no difference between the following pairs of tags : 
* `stable` and `latest`
* `stable-dind` and `dind`
* `stable-dind-rootless` and `dind-rootless`
* `stable-git` and `git`

I'm a bit confused by this behaviour, because I would expect `stable` versions to lag behind cutting-edge versions, so that people specifying `stable` would have … well, more stable behaviour (some issues fixed before reaching stable, more time to migrate for important changes, etc…)

So, is there something I'm missing ? If not, can we think about setting up something like that ?

Of course, the exact workflow would need to be discussed, since this is a non-trivial question, but here are several ideas :
* Keeping `stable` one minor version older than the corresponding cutting-edge tag
* Delaying non-security issues by a week to catch most issues

**Comment by tianon** [comment]
Docker used to have both a "stable" and an "edge" channel (still evidenced in https://download.docker.com/linux/static/).  Semi-recently, the edge channel was abandoned because the work of maintaining it was too high (and the folks on it typically really wanted nighties).

We should've dropped the alias entirely for 19.03; perhaps we'll do so for the next major release.

**Comment by toadjaune** [comment]
Okay, that makes sense !

I suppose it would be nice to get rid of these tags to avoid confusing people such as myself, but removing them could break a lot of stuff… I dunno.

Thanks for the quick answer !
