### ISSUE TITLE
DOCKER_HOST broken if tls disabled with dind

### ISSUE THREAD

**Issue by marcosnils** [docker-library/docker#194]
I'm running a `dind` container with DOCKER_TLS_CERTDIR="" but seems like `dind` entrypoint (below) set's `DOCKER_HOST` to `tcp://docker:2375`. In my case the `docker` cname doesn't exist either in the machine or in the hosts file, so the client just refuses to connect due to resolution error.

Is this intented? Seems like it broke backwards compatibility as I'd expect that setting DOCKER_TLS_CERTDIR to "" would make it work as before.

https://github.com/docker-library/docker/blob/92d278e671f32a9ee4a3c0668e46a41f4a3b74b0/docker-entrypoint.sh#L34

**Comment by yosifkit** [comment]
I'm slightly confused since you say you are running `dind` and yet link to the non-dind entrypoint (which is what is run if the first argument is not `dockerd`).

https://github.com/docker-library/docker/blob/4dd3f3fe1f263ea74cdc8bed6091008cf62ab751/dockerd-entrypoint.sh#L180-L183

Assuming that you are having problems connecting to a running non-tls `dind`, how are you running the client you are trying to connect with?

If running an `*-entrypoint.sh` via `docker exec`, it should just work since there will be the socket and line 34 will be skipped:

https://github.com/docker-library/docker/blob/4dd3f3fe1f263ea74cdc8bed6091008cf62ab751/docker-entrypoint.sh#L23-L24
https://github.com/docker-library/docker/blob/4dd3f3fe1f263ea74cdc8bed6091008cf62ab751/docker-entrypoint.sh#L30

If you are running from another container via `docker run`, then you need to run it in such a way that `docker` resolves to the correct network address\* or set `DOCKER_HOST` in the env on that `docker run`.

------

\* note the `--network-alias docker` for the `dind` container in the [Docker Hub docs](https://github.com/docker-library/docs/tree/6ba5d4165133678cd96078ca57359a8ae9ad6195/docker#start-a-daemon-instance)

**Comment by wglambert** [comment]
Assuming this has been resolved so going to close
