### ISSUE TITLE
Use docker in docker in K8S

### ISSUE THREAD

**Issue by estherxyz** [docker-library/docker#205]
Hi,
I try to use docker in docker in K8S to build docker image than push to private registry.
Because of self-cert, it will occur x509 error.
How can I set /etc/docker/daemon.json in docker in docker and execute in K8S?
`{
  "insecure-registries" : ["myregistrydomain.com:5000"]
}`

Or there are other param in pod can set about this?

below is my dind pod.yaml
```---
apiVersion: v1
kind: Pod
metadata:
  name: dind
spec:
  containers:
    - name: dind-cmd
      image: docker:18.05-dind
      command: ['sh', '-c', 'docker pull {PR}/image_name:tag']
      env:
      - name: DOCKER_HOST
        value: tcp://localhost:2375
    - name: dind
      image: docker:18.05-dind
      securityContext:
        privileged: true
```

Thanks.

**Comment by wglambert** [comment]
A [configmap](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/) should work?

**Comment by yosifkit** [comment]
Or just add `--insecure-registry myregistrydomain.com:5000` to the command of the dind container?

**Comment by wglambert** [comment]
Closing since this seems resolved 

If you have other questions you could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum

**Comment by naiduasn** [comment]
@estherxyz were you able to resolve the issue? i encountered the same and could not find a way to pass this as command args
