### ISSUE TITLE
dind behind a proxy

### ISSUE THREAD

**Issue by valvo** [docker-library/docker#23]
Hi,

I want to run dind behind a proxy.
How/Where can I configure the proxy-settings, when using linked containers of docker:1.12 and docker:dind ?

**Comment by tianon** [comment]
I _think_ this would involve setting `HTTP_PROXY` (and any other vars necessary) on the Docker-in-Docker container, and then _also_ on all containers run within Docker-in-Docker.  It might be easier to look into setting up a [transparent proxy](http://www.tldp.org/HOWTO/TransparentProxy.html) so that this can be handled more automatically (to avoid having to set environment variables on _every_ container which is launched or created everywhere).

Closing since this is a general Docker question, not something we can really "fix" in this image. :+1:
