### ISSUE TITLE
include bash in docker:dind image

### ISSUE THREAD

**Issue by davidkarlsen** [docker-library/docker#233]
Could you include bash in the `docker:dind` image?

**Comment by tianon** [comment]
It's not an exact duplicate, but I think the sentiment in https://github.com/docker-library/docker/pull/24#issuecomment-249728789 is still really relevant. 👍

**Comment by silverwind** [comment]
Why close? `/bin/bash` would be very useful for scripting while building docker images in `docker:dind` for example.

**Comment by tianon** [comment]
The short version is that Bash is not directly necessary for or used by Docker itself, so it is intentionally not included in order to keep the images as minimal as is reasonably possible.  It's straightforward for users to add additional packages (as you've noted), but ~impossible for users to _remove_ packages if we pre-include them.
