### ISSUE TITLE
Using docker push command cannot use cache in Drone CI

### ISSUE THREAD

**Issue by ywbjja** [docker-library/docker#234]
When I saw an article in docker docs[When I saw an article in docker docs](About storage drivers),I tried using docker volumes in Drone CI,But it doesn't work in docker push command
```bash
+ time docker push ***/***:0.0.1
The push refers to repository [***/***]
69e13f670501: Preparing
2ebbbbe18209: Preparing
9350ad1c5511: Preparing
ac1faac0988e: Preparing
dbc783c89851: Preparing
7bff100f35cb: Preparing
7bff100f35cb: Waiting
2ebbbbe18209: Layer already exists
dbc783c89851: Layer already exists
ac1faac0988e: Layer already exists
9350ad1c5511: Layer already exists
7bff100f35cb: Layer already exists
69e13f670501: Pushed
lastest: digest: sha256:e384928e209e5bbe9a3afd71f0983963f11db67c038118225898dc107c47f5ab size: 1576
real	0m 14.34s
user	0m 0.02s
sys	0m 0.01s
```
it took 14 seconds,,but when I use docker in centos 7 to push,it only took 1 second
```bash
time docker push ***/***:0.0.2
The push refers to repository [***/***]
ce7c4ab156d1: Layer already exists 
6c319642a278: Layer already exists 
18640f5271c3: Layer already exists 
ac1faac0988e: Layer already exists 
dbc783c89851: Layer already exists 
7bff100f35cb: Layer already exists 
0.0.1: digest: sha256:469fab477c72d2b9bceb2ca24271dfd5510f27cc651299a392d55df25959cbf5 size: 1576

real	0m1.311s
user	0m0.027s
sys	0m0.030s

```
So i don't know what went wrong.
This is my .drone.yml with Drone CI [https://drone.io/](drone)
```bash
- name: Docker build
  image: docker:latest
  pull: if-not-exists
  volumes:
  - name: docker
    path: /var/run/docker.sock

  commands:
    - docker version
    - docker login -u ***  --password *** ***
    - time docker build -f Dockerfile -t ***:0.0.1 .
    - time docker push ***:0.0.1
    - docker system prune -f
```
and this is my Dockerfile
```dockerfile
FROM openjdk:8u181-jdk-alpine
VOLUME /tmp
COPY ./target/lib/ ./lib/
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
COPY ./target/security-0.0.1-SNAPSHOT.jar security-java.jar
EXPOSE 8086
ENTRYPOINT ["java","-jar","-Xms128m","-Xmx256m","/security-java.jar"]
```
I put the external dependencies into the lib folder,I want to know if Drone CI is not supported 
Thinks.

**Comment by tianon** [comment]
I'm not sure I understand what this has to do with this image / repository?

This is the repository for the Docker official image on the Docker Hub (https://hub.docker.com/_/docker), while it appears your issue is something that's either specific to Drone CI (in which case it should be reported to them via https://discourse.drone.io/ which comes from the "Support" link at the bottom of https://drone.io/) or Docker itself.

In either case, I think you would be more likely to get the kind of help you're looking for by asking [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker), since this is more of a usage / expected functionality question than something we could fix in the Docker image directly.
