### ISSUE TITLE
Connection problem in docker:18.05.0-dind container inside minikube with driver=docker

### ISSUE THREAD

**Issue by amarchese96** [docker-library/docker#252]
I've started a pod with a docker:18.05.0-dind container in a kubernetes cluster launched with minikube using docker driver. When I exec into the pod and try to pull an image I get the following error:
Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp 127.0.0.1:443: connect: connection refused.

If I create instead a minikube cluster with driver=virtualbox it works.

Here the deployment that starts the pod:

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dind
  labels:
    app: dind
spec:
  selector:
    matchLabels:
      app: dind
  template:
    metadata:
      labels:
        app: dind
    spec:
      containers:
        - name: docker
          securityContext:
            privileged: true
          image: "docker:18.05.0-dind"
          ports:
            - containerPort: 2375

**Comment by wglambert** [comment]
You could try searching through https://github.com/kubernetes/minikube/issues since the issue appears to be exclusive to Minikube's drivers

The scope of the docker-library is essentially confined to changes made within the Dockerfile and Entrypoint, I don't see how we could alleviate this issue from the official-image's standpoint

**Comment by amarchese96** [comment]
Ok thank you for the help.
