### ISSUE TITLE
Docker/Install

### ISSUE THREAD

**Issue by Savagemikey92** [docker-library/docker#270]
$ sudo apt-get update

$ sudo apt-get install \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common

**Comment by wglambert** [comment]
Closing since this seems to have been opened by mistake

For questions about using or installing Docker you could try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
