### ISSUE TITLE
Adding docker images to docker-dind at build time

### ISSUE THREAD

**Issue by kaysond** [docker-library/docker#287]
I'm using `docker:dind` to test an iptables-based firewall that runs in docker (via host-mode networking typically, and network namespaces in swarm). The main reasons for using docker-in-docker are: 1) reproducible CI environment, and 2) not polluting iptables with testing on dev hosts.

Is there an easy way to include my image into the dind test environment image?

Right now I'm doing:
```
FROM docker:20.10.2-dind

RUN apk add --no-cache <dependencies>
COPY . /opt/repo
ENTRYPOINT /opt/repo/entrypoint.sh
```
and entrypoint.sh has

```
#!/usr/bin/env bash
/usr/local/bin/dockerd-entrypoint.sh dockerd &
while ! docker ps; do sleep 1; done #wait for docker to start up
docker build -t image1 /opt/repo/image1
docker build -t image2 /opt/repo/image2
sleep infinity
```
The third line shows the kind of problem I keep having: the image isn't actually finished until runtime. So I have to wait for the daemon to start up before building images. Similarly, when I run my test suite, I have to use another while loop to make sure the images are finished building.

Is there a better way?

**Comment by tianon** [comment]
See https://github.com/docker-library/docker/issues/148 for some previous discussion on this topic.

**Comment by kaysond** [comment]
Interesting thanks. But even with save/load, the final image still can't be added at build time, correct? I can include the tarball at build time, but would still have to use `docker load` at runtime?

Do I understand correctly that with https://github.com/moby/moby/issues/38043, I could build the image during development, and simply copy the files into the `docker:dind` filesystem?

**Comment by tianon** [comment]
Yeah, otherwise you're doing overlay on top of overlay, which may or may not work very well (if at all).

The thing that makes containerd better suited for this idea is that the downloaded/pristine image content vs the extracted content are separate (where those are the same store in Docker and the former has to be recreated if it's necessary for something like `docker save` or `docker push`), so the containerd content store could be filled up with image content without extracting it, and then it would only be extracted at runtime (which is a relatively fast operation compared with the build or pull).
