### ISSUE TITLE
does the docker:dind-rootless have to run with --privileged?

### ISSUE THREAD

**Issue by gyh9457** [docker-library/docker#291]
I do not want to run with --privileged, but i get an error : `[rootlesskit:parent] error: failed to start the child: fork/exec /proc/self/exe: operation not permitted`

**Comment by wglambert** [comment]
You still need `--privileged` https://github.com/docker-library/docker/issues/151#issuecomment-483185972

You'll also want the command set to `--experimental` for `dockerd`https://github.com/docker-library/docker/issues/281#issuecomment-744766015

Like `docker run -it --rm --privileged docker:dind-rootless --experimental`

**Comment by gyh9457** [comment]
thanks @wglambert

**Comment by mo-saeed** [comment]
@wglambert Perfect thank you, it works :)

I just have one question, runnning the container here as `privileged` expose the same risk as any other containers runnning as `privileged` or this is different? I just want to understand the risk here.

**Comment by wglambert** [comment]
Yeah it's essentially the same risk. Maybe a little bit minimized since `rootlesskit` provides a layer of security, but `--privileged` by nature gives the container all the capabilities as the host https://containerjournal.com/topics/container-security/why-running-a-privileged-container-is-not-a-good-idea/
