### ISSUE TITLE
Missing os/arch if using specific version tag

### ISSUE THREAD

**Issue by jokay** [docker-library/docker#325]
I would like to use the specific version tag but it lacks some os/arch *(linux/arm/v6, linux/arm/v7)*.

`:latest`

![image](https://user-images.githubusercontent.com/18613935/128308599-ab2cb846-3da1-40aa-8ddf-04bcdb71dd91.png)

`:20.10.8`

![image](https://user-images.githubusercontent.com/18613935/128308676-1abf0653-9c7b-4f43-b597-b53f63eb0610.png)

Would it be possible to have all os/arch from `:latest` in the specific version releases as well?

**Comment by yosifkit** [comment]
That'd be great, but those architectures have been failing to build for quite some time (duplicate of https://github.com/docker-library/docker/issues/260).  It's likely that we'll just disable the `arm32*` image builds since `latest` is pulling in their last successful build from ~1 year ago (https://hub.docker.com/r/arm32v7/docker/tags?page=1&ordering=last_updated&name=latest). They can definitely come back once the problem is fixed upstream.

```console
+ dockerd --version
Bus error (core dumped)
```

**Comment by jokay** [comment]
Thx for the information, will close the issue then :+1:
