### ISSUE TITLE
More detailed description on image version?

### ISSUE THREAD

**Issue by zzj0402** [docker-library/docker#340]
What's the base image system?
What is the rootless container?
Explain?

**Comment by wglambert** [comment]
The variants are Alpine and windowsservercore-1809 
https://github.com/docker-library/docs/tree/master/docker#simple-tags

The rootless variant runs as a non-root user
https://github.com/docker-library/docs/tree/master/docker#rootless
For more information on it see the linked thread https://github.com/docker-library/docker/pull/174

In the future questions like these are better asked over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum

**Comment by zzj0402** [comment]
Thanks for the explanation but I think it's better to put in the repo markdown. This is more related to what things are than “user-help”.
