### ISSUE TITLE
How to create docker volume on specific device("Lun")

### ISSUE THREAD

**Issue by sadatned** [docker-library/docker#341]
I have multiple devices ("LUNs") mapped to my linux server. These luns are mapped via FC (block devices) from VMAX storage.

I would like to create docker volume [ "docker volume create " command ] to create docker volume on specific Device ("LUN") but somehow I dont find option to create docker volume on specific device.
Any pointers would be great . Thanks in advance.

Devices ("LUNs") List
/dev/sdae
/dev/sdaf
/dev/sdag
/dev/sdah
/dev/sdai
/dev/sdaj
/dev/sdak
/dev/sdal
/dev/sdam
/dev/sdan
/dev/sdao
/dev/sdap
/dev/sdaq
/dev/sdar

docker volume create -d local -o size=4000g -o extended_fs_attr="bsize=8192" volume10

**Comment by wglambert** [comment]
This repo is for the Docker-in-Docker image https://hub.docker.com/_/docker

But you should be able to do `docker volume create --opt device=/dev/sdae` for instance https://docs.docker.com/engine/reference/commandline/volume_create/#driver-specific-options

For further help I'd try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
