### ISSUE TITLE
Docker on windows does not work

### ISSUE THREAD

**Issue by yahorsi** [docker-library/docker#363]
Hi Guys, when on windows, we use docker base image **docker:windowsservercore-ltsc2022** and run something simple like **docker -v**. It works, but then if we try to use **docker build .** then it fails with an error like:

```
error during connect: This error may indicate that the docker daemon is not running.: Post "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/images/create?fromImage=node&tag=lts": open //./pipe/docker_engine: The system cannot find the file specified.
```

**Comment by wglambert** [comment]
Hm, there was this issue on the Docker-for-win github https://github.com/docker/for-win/issues/8201

It looks like it went unresolved, you could either try making another issue on that repo or asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker) since these repos are for the official-images specifically and not Docker Desktop

(Also searching for this error came up with a lot of docker machine issues which you hopefully aren't using since it's deprecated https://docs.docker.com/machine/)

**Comment by yosifkit** [comment]
Duplicate of https://github.com/docker-library/docker/issues/49; the Docker daemon cannot run inside a Windows container. The image only contains the Docker client.
