### ISSUE TITLE
Doesn't work when host is a virtual machine

### ISSUE THREAD

**Issue by henriquehbr** [docker-library/docker#371]
I'm trying to run `docker:rc-dind-rootless` on Alpine Linux 3.16 (running inside a VirtualBox VM)

I've followed the steps on the documentation, first, i've executed:

```
docker run --rm --privileged --name dind -dt docker:rc-dind-rootless
```

And then:

```
docker exec -it dind docker-entrypoint.sh sh
```

The socket is never created at `/run/user/1000/docker.sock`, instead `DOCKER_HOST` is set to `tcp://docker:2376`, consequently making Docker commands fail with the `no such host` message

When checking the logs, the following error message appears:

```
Signature ok
subject=CN = docker:dind client
Getting CA Private Key
/certs/client/cert.pem: OK
Device "ip_tables" does not exist.
ip_tables              32768  2 iptable_filter,iptable_nat
x_tables               49152  6 xt_conntrack,xt_MASQUERADE,xt_addrtype,iptable_filter,iptable_nat,ip_tables
modprobe: can't change directory to '/lib/modules': No such file or directory
open: No such file or directory
[rootlesskit:child ] error: executing [[ip tuntap add name tap0 mode tap] [ip link set tap0 address 02:50:00:00:00:01]]: exit status 1
```

Strangely enough, it works fine on my Arch Linux (bare-metal) host, running, below are the versions of Docker that i'm running on each environment:

- bare-metal: `Docker version 20.10.17 (build 100c70180f)`
- vm: `Docker version 22.06.0 (build 3e9117b)`

Any clue of what might be happening? i wonder if the Docker version mismatch between both environments might be the one to blame

**Comment by wglambert** [comment]
I can't reproduce using Docker for Linux which uses Virtualbox
![image](https://user-images.githubusercontent.com/26428991/180872762-234ab5a1-cd55-48ca-b9ae-2de1b4eb0f31.png)

**Comment by henriquehbr** [comment]
I think Docker for Linux VMS's might have some minor differences from my virtualized host environment

I'm not sure if you have VirtualBox installed, but i've created a [image file](https://drive.proton.me/urls/EC61MC6ZW0#HUHw5lIii6SZ) (~400mb) so you can import the exact same virtual machine i used to reproduce this issue

In order to import it, go on File > Import Appliance > Load the file > Next > Import

There's a executable `reproduce-bug` shell script at the non-root user home directory that you can use to automatically run the commands to reproduce the issue, mentioned on my first comment, The root password is `toor`, there's also a non-root user `hbr` with the same password as root

**Comment by wglambert** [comment]
Docker Desktop for Linux might not be virtualbox as I was thinking but it is a VM https://docs.docker.com/desktop/install/linux-install/#why-docker-desktop-for-linux-runs-a-vm

Ultimately these repos try to reduce the issue to either an issue with the host's environment or something that is reproducible to then troubleshoot and resolve. So in this case since Docker offers Docker Desktop which runs containers in a VM, and it the image works as expected then it seems to be an issue with the host environment and unfortunately isn't something we can resolve since these repos aren't really a user-help forum for troubleshooting those nuances

I would try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker)

**Comment by henriquehbr** [comment]
Thanks for the explanation! i'll try asking on those you suggested instead
