### ISSUE TITLE
packages cant be installed in dind container

### ISSUE THREAD

**Issue by abhishekgupta2205** [docker-library/docker#385]
i am running dind image pod in kubernetes . i have created a container inside this container (pod)and now i want to add some packages inside this new container . but it is failing with this error .
![Screenshot from 2022-11-22 17-28-16](https://user-images.githubusercontent.com/68244292/203308396-ecd75513-a0fd-4674-828a-695441525946.png)

**Comment by abhishekgupta2205** [comment]
inside pod container i am able to run these commands.

**Comment by abhishekgupta2205** [comment]
also i am not able to debug more because i am unable to see logs of the conatiner(e2df) through docker logs command .
![Screenshot from 2022-11-23 13-33-59](https://user-images.githubusercontent.com/68244292/203497267-57648049-a1f5-47c1-9cdc-48e62a15be36.png)


output of docker info

![Screenshot from 2022-11-23 13-33-59](https://user-images.githubusercontent.com/68244292/203497281-c23e1292-3004-416c-bb45-5c13215de07e.png)

**Comment by tianon** [comment]
Instead of adding packages to a live running container, I would suggest using a `Dockerfile`:

```dockerfile
FROM docker:20.10-dind
RUN apk add --no-cache curl
```

In the future, these sorts of questions/requests would be more appropriately posted to a dedicated support forum, such as [the Docker Community Slack](https://dockr.ly/comm-slack), [Server Fault](https://serverfault.com/help/on-topic), [Unix & Linux](https://unix.stackexchange.com/help/on-topic), or [Stack Overflow](https://stackoverflow.com/help/on-topic).

**Comment by yosifkit** [comment]
Judging by the command that I can see in your `docker ps`, I'd guess that other `apk` is waiting for user input (or still installing things) and so is still holding the lock and thus you can't `docker exec` in and lock the same files.

But you really should be creating an image with the extra packages you need (like @tianon's Dockerfile example) and not installing them in a running ephemeral container.
