### ISSUE TITLE
When mount hostpath to /var/lib/docker on macos. docker build not work.

### ISSUE THREAD

**Issue by libinglong** [docker-library/docker#389]
docker run --rm  --privileged --net=host -e DOCKER_TLS_CERTDIR="" -v /Users/jack/docker:/var/lib/docker docker:dind

```Dockerfile
FROM ubuntu
RUN sleep 1
```

logs:

```txt
docker build -t test .
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM ubuntu
 ---> 6b7dfa7e8fdb
Step 2/2 : RUN sleep 1
operation not supported
```

Related issue:https://github.com/docker-library/docker/issues/342

**Comment by tianon** [comment]
Unfortunately for your use case, this is not going to be something we can likely support -- Docker has very particular requirements for the storage underneath `/var/lib/docker` and there's not really much we can do in the image to change that (nor even in Docker itself, to be honest -- is has these particular needs because the kernel functionality it instruments have them).
