### ISSUE TITLE
dind for aarch64?

### ISSUE THREAD

**Issue by vielmetti** [docker-library/docker#41]
I'm looking at running docker-in-docker for aarch64 (ARMv8). I don't see an officially supported version in the usual place (https://hub.docker.com/u/aarch64/docker/ is where I'd expect it). Suggestions and what to do next welcomed.

**Comment by alexellis** [comment]
👍 and for armhf.

@tianon is this within the realms of possibility?

**Comment by yosifkit** [comment]
We want to have more architectures, but we only grab the binaries as [released by docker](https://github.com/docker-library/docker/blob/b202ec7e529f5426e2ad7e8c0a8b82cacd406573/1.13/Dockerfile#L13), so until they release and support more we would have to recreate the build process. :cry:  There are `armel` and `i386` tar bundles on get.docker.com, but I am not sure if the `armel` binaries work and the `i366` tar only contains the client binary.

On a side note, we are working to integrate multiple architectures more directly into the official-images and hope to use manifest lists (or whatever the new name is) so that `docker pull docker:dind` will pull the correct architecture.  For more information see https://github.com/docker-library/official-images/issues/2289.

For the short term, to get more architectures, we'll continue to use [tianon's groovy repo](https://github.com/tianon/jenkins-groovy/tree/c5fd996fc02afbd903c04baf63c0dff52e9596be/dsl/docker-multiarch/images) as we list on [the official images repo](https://github.com/docker-library/official-images/tree/00c6e48e33b69c394237cf52db695785332a53b1#architectures-other-than-amd64).

**Comment by vielmetti** [comment]
Thanks @yosifkit . I have been coordinating with Olivier and Andrew to get a Jenkins server running on a 96-core Packet 2A ARMv8 machine for Docker use, if you or @tianon are not in touch with them yet about that resource it could help things along to make that connection.

**Comment by vielmetti** [comment]
Bumping this as still of interest @yosifkit

**Comment by tianon** [comment]
Docker has deprecated https://get.docker.com builds in favor of the new https://download.docker.com/linux/static/, which is what we now consume.  Once Docker Inc officially supports ARMv8 there, we will consume those official releases here. :+1:

**Comment by alexellis** [comment]
Hi when did get.docker.com get deprecated? (news to me) There is only one architecture at the new site url though.. so what do we do for the RPi etc tutorials?

**Comment by tianon** [comment]
I saw it in a Docker release announce mailing list email, but I don't know whether it's public anywhere (as I noted over on https://github.com/docker-library/docker/pull/54#issuecomment-303241783).

> **Important:** The Docker CE Edge versions 17.05 will be the last release published on https://get.docker.com, https://apt.dockerproject.org, and https://yum.dockerproject.org. Starting with the Docker CE Edge 17.06 release, all new packages will only be published on https://download.docker.com, and on Docker Store.

I'm not sure what the communication plans are for that, but I'd recommend contacting Docker, Inc for further guidance.  I _think_ the new APT repos still have `armhf` (it's just the static binaries getting the shaft), but I haven't confirmed that for sure.  Sorry! :confused: :disappointed:

**Comment by andrewhsu** [comment]
@alexellis the intended purpose of the get.docker.com script was for convenience to install the legacy `docker-engine` packages, but kinda grew in scope to other installation options. Now that we've finished the last release of docker-engine 17.05.0 we're looking at a way to provide an alternative convenience install script to help install just the `docker-ce` packages from download.docker.com for future versions. It's on our radar...intended for 17.06.0 release. In the meantime (you probably already know), install instructions: https://docs.docker.com/engine/installation/

**Comment by friism** [comment]
Just to add to @andrewhsu - we'll probably also host he the refactored install-helper script that we're building for `download.docker.com` on `get.docker.com` for backwards compatibility. As mentioned, this script will only install `docker-ce` packages.
