### ISSUE TITLE
Vulnerability - DIND image TAG not updated for 23-dind

### ISSUE THREAD

**Issue by raghu017** [docker-library/docker#418]
23-dind, 23.0-dind, 23.0.2-dind are pointing to 29f11c7c63c84a51c45901701c2d16336c9abc6365d3a69136884b3cf15e2cc9

This image has Containerd vulnerabilities that is resolved in 3351a0a8ce728f938f8c15ebbacf533fd0054317544ad74348b5c651e0502a31. Hub is also pointing to https://hub.docker.com/layers/library/docker/23-dind/images/sha256-3351a0a8ce728f938f8c15ebbacf533fd0054317544ad74348b5c651e0502a31 but the PULL is getting the older image.

Can you update the tag and also point to the correct hash?

Also when can we expect vulnerabilities CVE-2022-41723 and CVE-2023-26054 to be resolved?

**Comment by yosifkit** [comment]
The tags are pointing to the most up to date `23-dind` image, built just ~5 days ago. `29f11c7c63c84a51c45901701c2d16336c9abc6365d3a69136884b3cf15e2cc9` is the manifest list sha and so is equivalent to the architecture specific id `3351a0a8ce728f938f8c15ebbacf533fd0054317544ad74348b5c651e0502a31` for `amd64`. Unfortunately, Docker Hub doesn't show the manifest list sha anywhere, so see https://explore.ggcr.dev/?image=docker%3A23-dind.

As far the specific CVEs: 

- `CVE-2022-41723` was fixed in https://github.com/moby/moby/pull/45056, so it was included in the `23.0.2` release. It looks like `docker-buildx` plugin hasn't updated for this yet in the `v0.10` branch, which is where the Docker Hub scan is seeing it.
- `CVE-2023-26054` doesn't show up on Docker Hub, so it is likely already fixed.

**Comment by raghu017** [comment]
I understand the tags are pointing to the latest. But the pulled image 23-dind still has old version of packages and our vulnerability scan is flagging this image.

I found these old vulnerable packages using sbom

Containerd v1.6.16  CVE-2023-25173
golang.org/x/net v0.4.0 CVE-2022-41723
github.com/moby/buildkit v0.11.2 CVE-2023-26054

Has references to old packages been removed?

**Comment by tianon** [comment]
```console
$ docker run --rm --pull=always docker:23-dind sh -xc 'docker --version && dockerd --version && containerd --version && ctr --version && runc --version && docker buildx version && docker compose version'
23-dind: Pulling from library/docker
Digest: sha256:29f11c7c63c84a51c45901701c2d16336c9abc6365d3a69136884b3cf15e2cc9
Status: Image is up to date for docker:23-dind
+ docker --version
Docker version 23.0.2, build 569dd73
+ dockerd --version
Docker version 23.0.2, build 219f21b
+ containerd --version
containerd github.com/containerd/containerd v1.6.19 1e1ea6e986c6c86565bc33d52e34b81b3e2bc71f
+ ctr --version
ctr github.com/containerd/containerd v1.6.19
+ runc --version
runc version 1.1.4
commit: v1.1.4-0-g5fd4c4d
spec: 1.0.2-dev
go: go1.19.7
libseccomp: 2.5.1
+ docker buildx version
github.com/docker/buildx v0.10.4 c513d34049e499c53468deac6c4267ee72948f02
+ docker compose version
Docker Compose version v2.17.2
```

https://github.com/moby/moby/releases -> Docker 23.0.2 is the latest 23 release
https://github.com/containerd/containerd/releases -> there _is_ a 1.6.20 containerd release, but it doesn't contain any security-related updates
https://github.com/opencontainers/runc/releases -> there _is_ a 1.1.5 release of `runc`, and it _is_ security-related, but your tooling doesn't seem to be picking that up (which is the point at which we need to start questioning whether the tooling is telling you accurate information)
https://github.com/docker/buildx/releases -> 0.10.4 is the latest release of buildx available
https://github.com/docker/compose/releases -> 2.17.2 is the latest release of compose available

From the perspective of this image however, we faithfully publish what's provided by the relevant upstreams, and in our case both containerd and runc come from the published Docker static binaries on download.docker.com, so without a new release of Docker 23, they won't be updated (and the other two bits of software we embed are at the latest released versions we could possibly package).

**Comment by raghu017** [comment]
Sbom is reporting these images(filtered) 

docker sbom docker:23.0.2-dind
Syft v0.43.0
 ✔ Loaded image
 ✔ Parsed image
 ✔ Cataloged packages      [327 packages]
github.com/containerd/console                                                 v1.0.3                                    go-module
_github.com/containerd/containerd                                              v1.6.16-0.20230124210447-1709cfe273d9     go-module_
github.com/containerd/containerd                                              v1.6.19                                   go-module
github.com/containerd/continuity                                              v0.3.0                                    go-module
github.com/containerd/ttrpc                                                   v1.1.0                                    go-module
github.com/containerd/typeurl                                                 v1.0.2                                    go-module
_github.com/moby/buildkit                                                      v0.11.2                                   go-module_
github.com/moby/buildkit                                                      v0.11.5                                   go-module
_golang.org/x/net                                                              v0.4.0                                    go-module_
golang.org/x/net                                                              v0.7.0                                    go-module

**Comment by raghu017** [comment]
Any update? Old vulnerable images like containerd 1.6.16 are still there and scanner is no picking it up. Problem is still there with 23.03-dind image.

**Comment by tianon** [comment]
We're talking past each other -- let me try to be more clear: you need to take this up with your security scanning vendor or whoever set the policy that you must have "a 'clean' CVE scan" for all images.

The versions of the software we've packaged in this image are the latest versions available from the relevant upstreams who maintain them.

I do not believe the images we've published are _actually_ vulnerable from a functional perspective, but would welcome attempts to show otherwise (if you are able to demonstrate that the images are indeed vulnerable with an actual escalation, not just a CVE scanning tool, please report that responsibly via GitHub's security advisory feature).
