### ISSUE TITLE
empty manifests pushed to docker hub for 24.0.7

### ISSUE THREAD

**Issue by vladdblt** [docker-library/docker#454]
Example:
$ crane manifest docker:24.0.7-cli | jq
{
  "manifests": [],
  "mediaType": "application/vnd.oci.image.index.v1+json",
  "schemaVersion": 2
}
the same with the rest tags

**Comment by vladdblt** [comment]
Quite informative ref from closed #455:
> The tags exist, but no image layers: https://hub.docker.com/_/docker/tags?page=1&name=24.0.7

**Comment by yosifkit** [comment]
It is normal/possible in the Docker official images build pipelines for new tags to receive an empty image index (aka manifest list). This happens if the builds are slow or broken and usually is just temporary. In this case, the builds were stuck on a triggering job. I've fixed the issue and builds should be coming soon as each architecture finishes their respective image.

**Comment by henklars** [comment]
With all the automated pipelines out there i think it is a good practice to not publish at all if any of the artifacts is having issues. Lots of people, including me, gets a notification in renovate or similar whenever a new update is released and i don't think it should be necessary  to have a check if the new tag contains an image or not.
