### ISSUE TITLE
I can't copy a path that is ../ from my context

### ISSUE THREAD

**Issue by dugonzal** [docker-library/docker#491]
if I add a wildcard * if it lets me copy it, I think it's a parse error. 

 => ERROR [6/7] COPY ../I/ IEC61850forCSharp                                                                                                                                                                        0.0s 
------
 > [6/7] COPY ../I/ IEC61850forCSharp:
------
Dockerfile:20
--------------------
  20 | >>> COPY ../I/ IEC61850forCSharp
--------------------
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref 4f81d817-62c8-4e6c-84f9-879bf3c06130::bo9vhwl0nvmwsuqojk8eytl2t: "/I": not found
ERROR: Service 'goose_listener' failed to build : Build failed

**Comment by whalelines** [comment]
This repository is for the Official Image of the `docker` CLI and daemon, https://hub.docker.com/_/docker , whereas this is a Docker Build question. This question would be more appropriate for the Docker Community Slack, http://dockr.ly/comm-slack .

That said, this is expected behavior. Only the contents of the build context is sent to the builder. The contents of and build context parent directories are not sent and therefore not available to the build.
