### ISSUE TITLE
24.0.9-dind install python 3.12

### ISSUE THREAD

**Issue by dbwodlf3** [docker-library/docker#499]
docker:24-dind, 24.0.9 is using python 3.12. it install python 3.12.
some packages is broken on python 3.12

now i just docker:24.0.8-dind but, how can install python specific version on latest docker:24-dind?

**Comment by whalelines** [comment]
`docker:24-dind` is currently equivalent to the tags [`24.0.9-dind`, `24.0-dind`, `24-dind`, `24.0.9-dind-alpine3.20`, `24.0.9-git`, `24.0-git`, `24-git`, `24.0.9`, `24.0`, `24`, `24.0.9-alpine3.20`](https://github.com/docker-library/official-images/blob/0fde942138f2da077d05e71744d153be831a5dd4/library/docker#L75), which, as a few of the tags indicate, are based on Alpine 3.20. Alpine 3.20 only has Python packages for Python 3.12, https://pkgs.alpinelinux.org/packages?name=python3&branch=v3.20&repo=&arch=&maintainer= . Therefore, you would likely either need to find an alternative source for Alpine packages for a different version of Python, compile Python from source, or help/wait for the packages you are interested in to be fixed in Python 3.12.

**Comment by tianon** [comment]
Depending on what you're actually trying to accomplish (https://xyproblem.info/), there might also be a better way.  For example, whatever it is you're currently running _inside_ the `dind` container might be better suited to run in a sidecar container (or child container) with access to the Docker socket.
