### ISSUE TITLE
Questions about docker build 

### ISSUE THREAD

**Issue by haitang5445** [docker-library/docker#502]
docker version: 26.1.4

I have configured /etc/docker/daemon.json   insecure-registries: 192.168.1.100

now I can docker pull http  registries

but when I used docker build From 192.168.1.100/xxx/base-image ,It does tell me that the link is https://192.168.1.100/v2.....  tcp 192.168.1.100:443: connect: connection refused

**Comment by LaurentGoderre** [comment]
Are you sure your registry is available on `https`?

**Comment by tianon** [comment]
This repository contains the source for the `docker` Docker Official Image, https://hub.docker.com/_/docker, and is not a general resource for running Docker.

You can ask for help in the [Docker Community Slack](https://dockercommunity.slack.com/). If you are not already a member of the Docker Community Slack, you can use [this link to join](http://dockr.ly/comm-slack). You can find more support options at [Docker Support](https://www.docker.com/support/).

When you do ask for help, I would recommend including more detail about what you are trying to do, what commands you are running, and what errors are being reported.

(in general, I don't think `insecure-registries` automatically implies port 80 instead of 443, but I could be mis-remembering the implementation details)

Good luck!
