### ISSUE TITLE
How to update network properties? 

### ISSUE THREAD

**Issue by brunolnetto** [docker-library/docker#508]
Given a docker network `mynet`, is it possible to edit the properties available by command run `docker network inspect mynet`?

**Comment by tianon** [comment]
I think any properties there which are editable have to be set during network creation (ie, on `docker network create`).

That being said, this is the repository for the Docker-in-Docker official image (https://hub.docker.com/_/docker), so you might have better luck asking questions like this in a more generic Docker support forum (since your question isn't really specific to the Docker-in-Docker image maintained in this repository).
