### ISSUE TITLE
Reconsider defaulting to vfs storage driver?

### ISSUE THREAD

**Issue by AaronFriel** [docker-library/docker#88]
Right now, `:dind` images set `--storage-driver vfs` by default. As I understand it, Docker will automatically choose the best applicable driver on loading (e.g.: btrfs, zfs, overlay2). Is there a reason `:dind` images still default to vfs?

**Comment by tianon** [comment]
It was originally chosen because otherwise Docker would often default to `devicemapper`, which is awful if not manually configured appropriately.

Since then, the ordering in https://github.com/moby/moby/blob/226eb8004e0e9b1cd55b37ce4c235c0f19ca9a14/daemon/graphdriver/driver_linux.go#L54-L63 has improved to where I think it should be reasonably safe to remove `--storage-driver`. :+1:

Want to make a PR?

I think we should also do https://github.com/docker-library/docker/issues/86#issuecomment-336551411 to help improve this even further (such that kernel modules can be loaded if necessary to choose a more appropriate module, since the `/var/lib/docker` volume of the container might not be on the same storage as the host, and thus may still end up falling back to `devicemapper` otherwise).

**Comment by AaronFriel** [comment]
I can submit a PR, I think #86 might be out of scope, however. I don't want to require `dind` any more capabilities than absolutely necessary. Adding `modprobe` to entrypoint forces us to require `CAP_SYS_MODULE`.

**Comment by tianon** [comment]
Fixed by https://github.com/docker-library/docker/pull/89.
