### ISSUE TITLE
memory cgroup error since new docker-dind version

### ISSUE THREAD

**Issue by ajmulhollan1** [docker-library/docker#95]
Ever since the release of the latest docker-dind yesterday, all our builds using the `docker:dind` are failing.

Switching it back to `docker:17.09-dind` does fix this problem, but why is it happening?

Full error: 

`cgroups: memory cgroup not supported on this system: unknown`

**Comment by cl3m3nt666** [comment]
I had this problem with debian Jessie and docker 17.11.0-ce
Upgrade kernel worked for me ! :)

Upgrade Debian Jessie to Debian Stretch

**Comment by tianon** [comment]
Since this is an issue with upstream Docker, and not with the packaging provided by this image, I'm going to close this, but I'd recommend trying what @cl3m3nt666 suggested and/or following up with an upstream Docker issue (or hitting up [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker) for further help). :heart:
